version: '3'

services:
  
  web:
    build:
      context: .
      args:
        # Change these values if you want use a different user (or UID) than the current user (or current UID)
      
    volumes:
    # Uncomment for file changes to take effect while container is running
    - ./:/var/www/html/
    ports:
    - "80:80"
    environment:
      # DB settings
    
      # change these values if you want use a different user than the current user
      APACHE_RUN_USER: ${USER}
      APACHE_RUN_GROUP: ${USER}
    stdin_open: true
    tty: true
  phpmyadmin:
    